- name: Wait for SSH port to be available
  ansible.builtin.wait_for:
    host: "{{ ansible_host | default(inventory_hostname) }}"
    port: 22
    delay: 30
    timeout: 600
    state: started
  delegate_to: localhost
  become: false

- name: Reset ssh connection
  ansible.builtin.meta: reset_connection
