---
- name: Format the approved EFI partition
  ansible.builtin.command:
    argv: [mkfs.vfat, -F, '32', "{{ partition_prefix }}{{ idx + 1 }}"]
  when: item.fs_type == 'efi'

- name: Initialize the approved swap partition
  ansible.builtin.command:
    argv: [mkswap, "{{ partition_prefix }}{{ idx + 1 }}"]
  when: item.fs_type == 'swap'

- name: Create a fresh approved root filesystem
  ansible.builtin.command:
    argv: [mkfs.ext4, -F, "{{ partition_prefix }}{{ idx + 1 }}"]
  when: item.fs_type == 'ext4'
