- name: Log in to Concourse
  ansible.builtin.command:
    argv:
      - fly
      - -t
      - "{{ concourse_target }}"
      - login
      - -c
      - "{{ concourse_url }}"
      - -u
      - "{{ concourse_user }}"
      - -p
      - "{{ lookup('env', 'CONCOURSE_PASSWORD') }}"
  no_log: true
  delegate_to: localhost
