- name: API provision setup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set up servers in API
      include_role:
        name: provision
        tasks_from: create_server
      tags:
        - setup

- name: Infrastructure setup
  hosts: all
  gather_facts: false
  tasks:
    - name: General
      include_role:
        name: provision
        tasks_from: init_server
      tags:
        - setup

- name: Pre-provision setup
  hosts: all
  gather_facts: true
  tasks:
    - name: Set live environment fact
      ansible.builtin.set_fact:
        is_live_env: "{{ lookup('env', 'IS_LIVE_ENV') | default('1') == '0' }}"

    - name: Enter live environment
      when: not is_live_env | bool
      include_role:
        name: provision
        tasks_from: reboot
      vars:
        reboot_to_ipxe: true

    - name: Await and refresh
      include_role:
        name: provision
        tasks_from: await_and_refresh

- name: Provision
  hosts: all
  tasks:
    - name: Perform prereqs
      include_role:
        name: provision
        tasks_from: prereqs

    - name: Wipe the disk
      include_role:
        name: provision
        tasks_from: wipe
      when: should_wipe | bool | default(false)

    - name: Setup the disk
      include_role:
        name: provision
        tasks_from: partition

    - name: Bootstrap setup
      include_role:
        name: provision
        tasks_from: bootstrap

- name: Await server
  hosts: all
  gather_facts: false
  tasks:
    - name: Await and refresh
      include_role:
        name: provision
        tasks_from: await_and_refresh

- name: Post-provision setup
  hosts: all
  gather_facts: true
  tasks:
    - name: Post-provision setup
      include_role:
        name: provision
        tasks_from: post_provision