- name: API provision setup
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Set up servers in API
      include_role:
        name: provision
        tasks_from: create_server
      tags:
        - setup

- name: Infrastructure setup
  hosts: all
  gather_facts: false
  tasks:
    - name: General
      include_role:
        name: provision
        tasks_from: init_server
      tags:
        - setup

- name: Provision
  hosts: all
  tasks:
    - name: Perform prereqs
      include_role:
        name: provision
        tasks_from: prereqs

    - name: Wipe the disk
      include_role:
        name: provision
        tasks_from: wipe
      when: should_wipe | bool | default(false)

    - name: Setup the disk
      include_role:
        name: provision
        tasks_from: partition

    - name: Bootstrap setup
      include_role:
        name: provision
        tasks_from: bootstrap

- name: Await server
  hosts: all
  gather_facts: false
  tasks:
    - name: Wait for SSH port to be available
      ansible.builtin.wait_for:
        host: "{{ ansible_host | default(inventory_hostname) }}"
        port: 22
        delay: 30
        timeout: 600
        state: started
      delegate_to: localhost
      become: false

    - name: Remove the stale local ssh known_hosts entry
      ansible.builtin.shell: ssh-keygen -R "{{ ansible_host | default(inventory_hostname) }}" && ssh-keygen -R "{{ inventory_hostname }}"
      delegate_to: localhost
      become: false
      failed_when: false

    # - name: Clear SSH control sockets
    #   ansible.builtin.shell: rm -f ~/.ansible/cp/*{{ inventory_hostname }}*
    #   delegate_to: localhost
    #   become: false
    #   failed_when: false

    # - name: Add new host key to known_hosts
    #   ansible.builtin.shell: ssh-keyscan -H "{{ ansible_host | default(inventory_hostname) }}" >> ~/.ssh/known_hosts
    #   delegate_to: localhost
    #   become: false
    #   failed_when: false

    - name: Reset ssh connection
      ansible.builtin.meta: reset_connection

    # - name: Wait a moment for SSH to fully stabilize
    #   ansible.builtin.pause:
    #     seconds: 5


- name: Post-provision setup
  hosts: all
  gather_facts: true
  tasks:
    - name: Post-provision setup
      include_role:
        name: provision
        tasks_from: post_provision