---
- name: Check for the generated Compose file
  ansible.builtin.stat:
    path: "{{ mounted_data_path }}/docker-compose.yml"
  register: docker_compose_file

- name: Remove the infrastructure Compose project
  community.docker.docker_compose_v2:
    project_src: "{{ mounted_data_path }}"
    project_name: infra
    state: absent
    remove_volumes: true
    remove_images: all
    remove_orphans: true
  when: docker_compose_file.stat.exists

- name: Remove generated and downloaded platform files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ mounted_data_path }}/acme/acme.sh"
    - "{{ mounted_data_path }}/nginx/files/arch_netboot"
    - "{{ mounted_data_path }}/nginx/files/arch_iso"
    - "{{ mounted_data_path }}/nginx/files/debian_trixie_netboot"
    - "{{ mounted_data_path }}/nginx/files/debian_trixie_iso"
    - "{{ mounted_data_path }}/nginx/default.conf"
    - "{{ mounted_data_path }}/nginx/files/ipxe.iso"
    - "{{ mounted_data_path }}/nginx/files/ipxe.efi"
    - "{{ mounted_data_path }}/openbao/data"
    - "{{ mounted_data_path }}/openbao/init"
    - "{{ mounted_data_path }}/registry/config/config.yml"
    - "{{ mounted_data_path }}/registry/data"
    - "{{ mounted_data_path }}/docker-compose.yml"

- name: Remove the macvlan host shim
  become: true
  ansible.builtin.command:
    cmd: ip link delete macvlan-shim
  register: remove_macvlan_shim
  failed_when: false
  changed_when: remove_macvlan_shim.rc == 0
  when:
    - network_driver == "macvlan"
    - ansible_facts['os_family'] not in ["Darwin", "Windows"]
