---
- name: Read the publication Git repository
  ansible.builtin.uri:
    url: >-
      {{ lookup('env', 'STIGMERGY_API_URL') }}/api/v1alpha1/git-repositories/{{ inventory_publication.spec.destinationRef.name }}
    method: GET
    status_code: 200
  register: publication_repository

- name: Render the publication pipeline
  ansible.builtin.template:
    src: provision-group-commands.yml.j2
    dest: "/tmp/commands-{{ inventory_publication.metadata.name }}.yml"
    mode: "0600"

- name: Configure the publication pipeline
  ansible.builtin.command:
    argv:
      - fly
      - -t
      - "{{ concourse_target }}"
      - set-pipeline
      - -p
      - "commands-{{ inventory_publication.spec.inventoryCaptureGroupRef.name }}"
      - --non-interactive
      - -c
      - "/tmp/commands-{{ inventory_publication.metadata.name }}.yml"

- name: Unpause the publication pipeline
  ansible.builtin.command:
    argv:
      - fly
      - -t
      - "{{ concourse_target }}"
      - unpause-pipeline
      - -p
      - "commands-{{ inventory_publication.spec.inventoryCaptureGroupRef.name }}"
